apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-nginx-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dev-dull/argo-deploy.git
    targetRevision: HEAD
    path: dev/nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: my-nginx-dev
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
