apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dev-dull/argo-deploy.git
    targetRevision: HEAD
    path: sample
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-apps
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
