apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: truenas-nfs
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: k8s-sigs.io/nfs-subdir-external-provisioner
parameters:
  pathPattern: "192.168.11.10/mnt/TANK/fileserver/k8s_data" # waits for nfs.io/storage-path annotation, if not specified will accept as empty string.
  onDelete: delete