apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: truenas-nfs
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: example.com/external-nfs
parameters:
  server: 192.168.1.2
  path: /k8s_data
  readOnly: "false"