apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: my-nginx
        volumeMounts:
        - mountPath: /var/www/html
          name: pod-claim
  volumes:
  - name: pod-claim
    persistentVolumeClaim:
      claimName: my-nginx-pvc