apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: my-nginx
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: nginx-home
      volumes:
      # - name: pod-claim
      #   persistentVolumeClaim:
      #     claimName: my-nginx-pvc
      - name: nginx-home
        persistentVolumeClaim:
          claimName: my-nginx-pvc
