apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  replicas: 0
  template:
    spec:
      containers:
      - name: my-nginx
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: nginx-home
      volumes:
      - name: pod-claim
        persistentVolumeClaim:
          claimName: my-nginx-pvc
      - name: nginx-home
        nfs:
          server: 192.168.11.10
          path: /mnt/TANK/fileserver/k8s_data/nginx
